type Link {
    url: String!
    name: String!
    description: String!
    items: [Item!]@relation
    archived: Boolean
}

type Item {
    name: String!
    vendor: String!
    due_date: String!
    sales_tax_rate: Float
    quantity: Int!
    item_number: String!
    description: String!
    unit_cost: Float!
    unit_sales_price: Float!
    insurance_needed: Boolean
    tax_needed: Boolean
    link: Link
}

type Query {
    allLinks: [Link!]
    allItems: [Item!]
}